process_dir: processed  # directory for torch geometric processed dataset
cache_dir: cache  # directory for infinite summation processed files
checkpoint_dir: checkpoint  # directory for checkpoints

dataset: megnet
# JARVIS dataset: dft_3d
# MP dataset: megnet
target: shear modulus
# JARVIS dataset entries: formation_energy_peratom, mbj_bandgap, optb88vdw_bandgap, optb88vdw_total_energy, ehull
# MP dataset entries: e_form, gap pbe , bulk modulus, shear modulus
# If using custom dataset, please set this to the corresponding entry name, e.g., target

atom_features: cgcnn

# epochs: 500
epochs: 1000
#batch_size: 64
batch_size: 64

# num_workers: 8
num_workers: 0
# weight_decay: 0.0
weight_decay: 1e-5
learning_rate: 2e-4

criterion: l1
optimizer: adamw
scheduler: onecycle
# scheduler: none


pin_memory: False
write_checkpoint: True
write_predictions: True
store_outputs: True
progress: True
#log_tensorboard: False
log_tensorboard: True

normalize: False  # scaling the targets by their mean and std
euclidean: False  # disable infinite summation or not
cutoff: 4.0  # local graph cutoff
max_neighbors: 16
infinite_funcs: ["zeta", "zeta", "exp"]
infinite_params: [0.5, 3.0, 3.0]  # Coulomb, London dispersion, Pauli
R: 3  # half of the grid length
ksteps: 16 # rrwp

model:
  name: gsmnet
  conv_layers: 3
  rbf_min: -4.0
  rbf_max: 4.0
  potentials: [-0.801, -0.074, 0.145]  # coefficients for infinite summations; should be negative, negative, positive w.r.t. their mathematical form
#  potentials: [ -0.703, -0.0617, 0.142 ]
#  potentials: [-0.816, -0.052, 0.149]
  charge_map: False  # if including information of periodic table
  transformer: True  # enable transformer structure for infinite potential summation; only works when euclidean is False
  ssm: True  # enable SSM structure for infinite potential summation; only works when euclidean is False and transformer is True
  ksteps: 16 # RRWP

  # Mamba SSM 参数
  mamba_d_state: 128   # SSM 状态维度
  # mamba_d_state: 64   # 实际上64足够
  mamba_d_conv: 4     # 卷积核大小
  mamba_expand: 4     # 内部扩展倍数
  # mamba_expand: 2     # 实际上2足够
  mamba_dt_rank: "auto"  # 时间步长投影维度，可以设置具体整数
  mamba_dt_min: 0.001  # 最小时间步长
  mamba_dt_max: 0.1    # 最大时间步长
  mamba_dropout: 0.1   # Mamba 模块的 dropout 率
